# Generated by Django 4.2.29 on 2026-03-31 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('pcap', 'PCAP 離線分析'), ('live', '即時擷取')], max_length=10)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('pcap_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packet_count', models.IntegerField(default=0)),
                ('alert_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CNNResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField()),
                ('normal_count', models.IntegerField(default=0)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('avg_normal_error', models.FloatField(default=0)),
                ('avg_attack_error', models.FloatField(default=0)),
                ('heatmap_image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cnn_result', to='analyzer.analysissession')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('src_ip', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('suggestion', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='analyzer.analysissession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
